services:
  postgres:
    image: postgres:17.4
    container_name: library_db
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=libadmin
      - POSTGRES_PASSWORD=libpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U libadmin -d library"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
