services:
  postgres:
    image: postgres:15.0
    environment:
      - POSTGRES_DB=multitenant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration/V1_1__init_tenant1.sql:/docker-entrypoint-initdb.d/V1_1__init_tenant1.sql
      - ./src/main/resources/db/migration/V1_2__init_tenant2.sql:/docker-entrypoint-initdb.d/V1_2__init_tenant2.sql
    networks:
      - multitenant-network

volumes:
  app-data:
  postgres-data:

networks:
  multitenant-network:
    driver: bridge